---
title: "Bahrain map"
author: "James David Smith"
date: "22 January 2019"
output: html_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "docs", output_file ="index.html") }) 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list = ls())

library(sf)
library(devtools)
install_github("ropensci/osmdata")
library(osmdata)
library(tidyverse)
library(rnaturalearth)
```

### Map code

```{r, message=F, warning=F, fig.height=10, fig.width=8}
outline   <-ne_states(country = 'bahrain', returnclass='sf') %>% 
              select(name_en) %>% 
              mutate(pop = c(547983, 342315, 287434, 287434, 245994),
                     name = c('Capital', 'Northern', 'Southern', 'Southern', 'Muharraq')) %>%
              select(pop, name) %>%
              group_by(name) %>%
              summarise(pop = mean(pop))

roads     <- opq(bbox = st_bbox(outline)) %>%
              add_osm_feature(key ='highway', value = c("trunk", "primary", "motorway"), value_exact = T) %>%
              osmdata_sf(quiet = FALSE) %>%
              unique_osmdata()
roads     <-  roads$osm_lines

ggplot(outline) + 
  geom_sf(aes(fill = as.factor(pop))) + 
  geom_sf(data=st_intersection(roads,outline), colour= 'white') +
  scale_fill_discrete(name = "2016 Population") +
  coord_sf(datum = NA) +
  theme(panel.background = element_rect(fill = 'light blue'),
        legend.position = c(0.25, 0.15),
        legend.background = element_rect(fill = NA),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 16))
```


